### PR TITLE
Report downports as critical

### PR DESCRIPTION
**Pull request by rgildein**
To test CI for #183

### CODE REVIEW

**Comment by samuelallan72** [comment]
@rgildein why didn't the command comment work ( https://github.com/canonical/charm-openstack-service-checks/pull/183#issuecomment-2402700735 )?

**Comment by chanchiwai-ray** [comment]
> @rgildein why didn't the command comment work ( [#183 (comment)](https://github.com/canonical/charm-openstack-service-checks/pull/183#issuecomment-2402700735) )?

Our CI depends on GH secret

**Comment by samuelallan72** [comment]
> Our CI depends on GH secret

I thought the command comment was designed to be the confirmation to run the CI and share secrets with the CI run?

**Comment by chanchiwai-ray** [comment]
> I thought the command comment was designed to be the confirmation to run the CI and share secrets with the CI run?

That's two different things: the comment is for passing the compliance check; the secret not accessible by forks is an GitHub [security feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)(?)

**Comment by rgildein** [comment]
> I thought the command comment was designed to be the confirmation to run the CI and share secrets with the CI run?

No it was design, that we can enable CI only. However, since it's running from fork it will not work.

**Comment by gabrielcocenza** [comment]
Closing because the CI passed and we already merged #183

**Pull request closed without merging**
